// src/services/playLocalStore.ts
//
// On-device-only store for Play lessons generated by the LiteRT (E2B) path.
// When the student is offline, the cloud /play/lessons endpoint isn't
// reachable, so the lesson the on-device generator built lives here and is
// served back to PlayLibrary / PlayPreview / PlayGame from local storage.
//
// IDs are prefixed with `local_` so cloud and local lessons share an id
// space without collision risk. A wrapper layer in services/play.ts
// dispatches by prefix:
//   - id starts with 'local_' → AsyncStorage (this module)
//   - else                    → cloud /play/lessons/<id>
//
// listLessons merges both sources so the library is one continuous list.
//
// Reconciliation with the cloud (i.e. uploading local lessons once back
// online) is intentionally NOT done here yet — we want offline to be
// fully self-contained first. A future pass can add a sync worker that
// promotes local lessons to cloud and removes the local copy.

import AsyncStorage from '@react-native-async-storage/async-storage';
import type { PlayLesson } from '../play/types';

const STORAGE_KEY = 'neriah_play_local_lessons_v1';
const LOCAL_ID_PREFIX = 'local_';

/** Stable, sortable, no-deps id with the local prefix. */
function mintLocalId(): string {
  const ts = Date.now().toString(36);
  const rnd = Math.random().toString(36).slice(2, 8);
  return `${LOCAL_ID_PREFIX}${ts}${rnd}`;
}

export function isLocalLessonId(id: string): boolean {
  return typeof id === 'string' && id.startsWith(LOCAL_ID_PREFIX);
}

async function readAll(): Promise<PlayLesson[]> {
  try {
    const raw = await AsyncStorage.getItem(STORAGE_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    if (!Array.isArray(parsed)) return [];
    return parsed as PlayLesson[];
  } catch {
    return [];
  }
}

async function writeAll(lessons: PlayLesson[]): Promise<void> {
  await AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(lessons));
}

export interface SaveLocalLessonInput {
  title: string;
  subject?: string;
  grade?: string;
  source_content: string;
  questions: PlayLesson['questions'];
  was_expanded?: boolean;
  owner_id?: string;
}

/** Persist a freshly-generated lesson and return the canonical row. */
export async function saveLocalLesson(input: SaveLocalLessonInput): Promise<PlayLesson> {
  const now = new Date().toISOString();
  const lesson: PlayLesson = {
    id: mintLocalId(),
    title: input.title,
    subject: input.subject ?? null,
    grade: input.grade ?? null,
    owner_id: input.owner_id ?? '',
    owner_role: 'student',
    source_content: input.source_content,
    questions: input.questions,
    question_count: input.questions.length,
    was_expanded: !!input.was_expanded,
    created_at: now,
    shared_with_class: false,
    allow_copying: false,
    class_id: null,
    status: 'ready',
    origin: 'mine',
  } as PlayLesson;

  const all = await readAll();
  // Newest first so the library list reads naturally without a sort.
  await writeAll([lesson, ...all]);
  return lesson;
}

export async function getLocalLesson(id: string): Promise<PlayLesson | null> {
  if (!isLocalLessonId(id)) return null;
  const all = await readAll();
  return all.find((l) => l.id === id) ?? null;
}

export async function listLocalLessons(): Promise<PlayLesson[]> {
  return readAll();
}

export async function deleteLocalLesson(id: string): Promise<void> {
  if (!isLocalLessonId(id)) return;
  const all = await readAll();
  await writeAll(all.filter((l) => l.id !== id));
}
