#!/usr/bin/env bash
# install-litert-frameworks.sh
#
# Copies all vendored LiteRT-LM native artifacts into the react-native-litert-lm
# node_modules folder where CocoaPods and Gradle expect them. Covers iOS
# XCFramework + EngineInit shim + C++ wrapper + podspec, AND the Android
# vendored AAR + patched module-level build.gradle.
#
# Why this script exists: the upstream package has a postinstall that
# tries to download a prebuilt XCFramework from
# `github.com/hung-yueh/react-native-litert-lm/releases/download/vX.Y.Z/`,
# but no version 0.1.0 through 0.3.4 has ever published that asset
# (HTTP 404 confirmed Apr 2026). Without the framework, iOS builds link
# nothing and the LiteRT-LM Nitro module fails to resolve at runtime.
#
# So we keep our own prebuilt XCFramework in `vendor/litert-ios/`,
# committed to git, and copy it into node_modules on every `npm install`
# (chained from package.json's postinstall hook).
#
# This script is a no-op on non-macOS hosts because the upstream package
# only ships iOS native code on darwin anyway.

set -euo pipefail

if [ "$(uname)" != "Darwin" ]; then
  echo "[litert-ios] non-macOS host, skipping iOS framework install."
  exit 0
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
VENDORED="$PROJECT_ROOT/vendor/litert-ios/LiteRTLM.xcframework"
DEST_DIR="$PROJECT_ROOT/node_modules/react-native-litert-lm/ios/Frameworks"

if [ ! -d "$VENDORED" ]; then
  echo "[litert-ios] No vendored XCFramework at $VENDORED — skipping (run scripts/build-ios-engine.sh in node_modules to build one and commit it)."
  exit 0
fi

if [ ! -d "$PROJECT_ROOT/node_modules/react-native-litert-lm" ]; then
  echo "[litert-ios] react-native-litert-lm not in node_modules — skipping."
  exit 0
fi

mkdir -p "$DEST_DIR"

# Skip the XCFramework copy if the destination already has the same
# binary (large directory copy — only worth doing when there's a real
# change). Compare the device-slice binary by content, not Info.plist
# — Info.plist is regenerated by the build script with stable
# contents, so plist equality doesn't imply binary equality. This
# bit us once after a rebuild: vendor had the new framework, plist
# matched, copy was skipped, node_modules kept stale binary.
SRC_BIN="$VENDORED/ios-arm64/LiteRTLM.framework/LiteRTLM"
DEST_BIN="$DEST_DIR/LiteRTLM.xcframework/ios-arm64/LiteRTLM.framework/LiteRTLM"
if [ -d "$DEST_DIR/LiteRTLM.xcframework" ] && \
   [ -f "$SRC_BIN" ] && [ -f "$DEST_BIN" ] && \
   cmp -s "$SRC_BIN" "$DEST_BIN"; then
  echo "[litert-ios] XCFramework already in place, skipping copy."
else
  echo "[litert-ios] Copying LiteRTLM.xcframework into node_modules..."
  rm -rf "$DEST_DIR/LiteRTLM.xcframework"
  cp -R "$VENDORED" "$DEST_DIR/LiteRTLM.xcframework"
fi

# Sync cpp/include/litert_lm_engine.h with the vendored XCFramework's
# authoritative header. The npm package ships a stale 509-line copy
# under cpp/include/ from upstream v0.3.4 that uses the old short-name
# API (InputData, kInputText, kTopP). Our vendored XCFramework is a
# newer build with the verbose-name API (LiteRtLmInputData,
# kLiteRtLmInputDataTypeText, kLiteRtLmSamplerTypeTopP), and the
# patched HybridLiteRTLM.cpp targets the new names — so without this
# sync the build picks up the stale include and 5 symbols fail to
# resolve at compile time. Both XCFramework slices ship identical
# headers, so we copy from ios-arm64.
SRC_HEADER="$VENDORED/ios-arm64/LiteRTLM.framework/Headers/litert_lm_engine.h"
DEST_HEADER="$PROJECT_ROOT/node_modules/react-native-litert-lm/cpp/include/litert_lm_engine.h"
if [ -f "$SRC_HEADER" ] && [ -d "$(dirname "$DEST_HEADER")" ]; then
  cp "$SRC_HEADER" "$DEST_HEADER"
  echo "[litert-ios] Synced cpp/include/litert_lm_engine.h with vendored framework."
fi

# Vendored Hybrid wrapper patches:
#   - tryCreateEngine accepts a third audioBackend arg and we call it with
#     nullptr, nullptr for vision and audio. Skips multimodal executor
#     init that crashes on iOS because the Bazel-built XCFramework lacks
#     vision and audio ops.
#   - createNewConversation / sendMessageInternal / sendMessageAsync use
#     the Session API (litert_lm_engine_create_session +
#     session_generate_content). The Conversation API constructs a
#     re2::RE2 from the model's chat-template string, which crashes for
#     vision-aware Gemma 4 on our XCFramework (heap corruption when
#     vision_executor is null). Session API skips the prompt-template
#     compile entirely; we wrap the prompt in <start_of_turn>…<end_of_turn>
#     manually so Gemma 4 still gets a proper instruction turn.
#   - Header gains LiteRtLmSession* session_ field and StreamContext
#     gains promptBuffer to keep the formatted prompt alive across the
#     async streaming callback.
#   - Three calls to litert_lm_get_last_error() commented out (symbol not
#     in our XCFramework export list).
# We vendor the whole files instead of carrying a patch, because
# patch-package failed to parse the diff for this version of the package.
PATCHED_CPP="$PROJECT_ROOT/vendor/litert-cpp/HybridLiteRTLM.cpp"
DEST_CPP="$PROJECT_ROOT/node_modules/react-native-litert-lm/cpp/HybridLiteRTLM.cpp"
if [ -f "$PATCHED_CPP" ] && [ -d "$(dirname "$DEST_CPP")" ]; then
  cp "$PATCHED_CPP" "$DEST_CPP"
  echo "[litert-ios] Replaced HybridLiteRTLM.cpp with vendored patched copy."
fi

PATCHED_HPP="$PROJECT_ROOT/vendor/litert-cpp/HybridLiteRTLM.hpp"
DEST_HPP="$PROJECT_ROOT/node_modules/react-native-litert-lm/cpp/HybridLiteRTLM.hpp"
if [ -f "$PATCHED_HPP" ] && [ -d "$(dirname "$DEST_HPP")" ]; then
  cp "$PATCHED_HPP" "$DEST_HPP"
  echo "[litert-ios] Replaced HybridLiteRTLM.hpp with vendored patched copy."
fi

# EngineInit per-slice archives. Each contains just engine_impl.o
# extracted from the corresponding framework slice, force-loaded by
# the patched podspec so the LITERT_LM_REGISTER_ENGINE static
# initialiser survives Apple's linker dead-code stripping. These
# MUST stay in sync with the vendored framework — extracting from
# v0.10.1's framework but linking v1.x's framework yields ABI errors
# (engine_impl.o references absl::lts_X while the framework defines
# absl::lts_Y). The rebuild-litert-xcframework.sh script always
# re-extracts both pieces in lockstep.
ENGINE_INIT_SRC="$PROJECT_ROOT/vendor/litert-ios/EngineInit"
ENGINE_INIT_DEST="$PROJECT_ROOT/node_modules/react-native-litert-lm/ios/EngineInit"
if [ -d "$ENGINE_INIT_SRC" ]; then
  rm -rf "$ENGINE_INIT_DEST"
  cp -R "$ENGINE_INIT_SRC" "$ENGINE_INIT_DEST"
  echo "[litert-ios] Installed EngineInit per-slice archives."
fi

# Vendored podspec — patches s.user_target_xcconfig with the
# -force_load on the per-slice EngineInit/libengine_init.a so the
# engine registration symbol survives the final app link.
PATCHED_PODSPEC="$PROJECT_ROOT/vendor/litert-podspec/react-native-litert-lm.podspec"
DEST_PODSPEC="$PROJECT_ROOT/node_modules/react-native-litert-lm/react-native-litert-lm.podspec"
if [ -f "$PATCHED_PODSPEC" ] && [ -f "$DEST_PODSPEC" ]; then
  cp "$PATCHED_PODSPEC" "$DEST_PODSPEC"
  echo "[litert-ios] Replaced podspec with vendored patched copy (-force_load applied)."
fi

# Drop the upstream LiteRTLMAutolinking.mm. Our vendored podspec uses
# -force_load on EngineInit/libengine_init.a to register the engine, so
# the upstream auto-linking helper is dead code; leaving it in the source
# set causes a duplicate-symbol link when EngineInit's static initialiser
# also fires. Previously deleted via patch-package, but the patch failed
# on EAS build servers because the diff also embedded the entire
# XCFramework as binary blobs (which the install script copies instead).
STALE_AUTOLINKING="$PROJECT_ROOT/node_modules/react-native-litert-lm/ios/LiteRTLMAutolinking.mm"
if [ -f "$STALE_AUTOLINKING" ]; then
  rm -f "$STALE_AUTOLINKING"
  echo "[litert-ios] Removed upstream LiteRTLMAutolinking.mm (replaced by -force_load in vendored podspec)."
fi

# ── Android: replace the Maven dep with a local Maven repo ──────────────────
# Strategy: stop depending on com.google.ai.edge.litertlm:litertlm-android from
# Google Maven and instead serve our HEAD-of-main rebuild from a local Maven
# repo at vendor/litert-android-maven/. The canonical AAR file is
# vendor/litert-android/litertlm-android.aar (Bazel output, tracked in git);
# this script (re)populates the Maven-layout staging dir on each install:
#
#   vendor/litert-android-maven/
#     com/google/ai/edge/litertlm/litertlm-android/<version>/
#       litertlm-android-<version>.aar   (copy of vendor/litert-android/...)
#       litertlm-android-<version>.pom   (hand-written, mirrors Google Maven)
#
# History — what we used to do, and why we stopped:
#   - Old approach: keep the Maven dep on Google Maven for classes.jar, drop
#     our .so files into the library's src/main/jniLibs/, then `zip -d` the
#     same .so paths out of the cached Maven AAR to avoid duplicate-.so AGP
#     merge errors. That worked until the Gradle transform cache state went
#     out of sync — Gradle still held metadata.bin/results.bin pointing at a
#     `transformed/<artifact>/` directory we had partly wiped, and the next
#     build failed with
#       ManifestMerger2$MergeFailureException:
#         AndroidManifest.xml (No such file or directory)
#     The fundamental problem was mutating an artifact Gradle considers
#     immutable — there is no way to make Gradle's transform cache aware
#     of the change.
#   - flatDir attempt: works inside the library's classpath but Gradle
#     can't propagate a flatDir-resolved dep up to the consuming app's
#     classpath because flatDir entries don't have proper Gradle metadata.
#     The :app project then fails with "Could not find :litertlm-android:".
#   - Current approach (a real local Maven repo) gives Gradle full
#     coordinates + transitive metadata, the dep flows up to :app cleanly,
#     and the canonical AAR file stays untouched.
#
# This block:
#   - (Re)builds vendor/litert-android-maven/<coord>/ from the canonical AAR
#   - Copies the vendored build.gradle (it points at the local Maven repo)
#   - Copies the two patched Kotlin files
# No .so extraction. No AAR mutation. No transform cache wiping.
#
# Skipped silently when the rebuild hasn't been run yet.
VENDOR_AAR="$PROJECT_ROOT/vendor/litert-android/litertlm-android.aar"
ANDROID_DIR="$PROJECT_ROOT/node_modules/react-native-litert-lm/android"
if [ -f "$VENDOR_AAR" ] && [ -d "$ANDROID_DIR" ]; then
  # Resolve the LiteRT-LM version pin from the package.json so the local
  # Maven repo coord matches what build.gradle resolves.
  PKG_JSON="$PROJECT_ROOT/node_modules/react-native-litert-lm/package.json"
  LITERT_VER="$(node -e "console.log(require('$PKG_JSON').litertLm.androidMavenVersion)" 2>/dev/null || echo "")"
  if [ -z "$LITERT_VER" ]; then
    echo "[litert-android] ✗ Could not read litertLm.androidMavenVersion from package.json — skipping."
  else
    # (Re)build the local Maven repo staging dir. We always wipe + recreate
    # so a freshly rebuilt AAR (different mtime/contents) propagates cleanly
    # — Gradle's transform cache picks up file changes here without any
    # manual cache wipe, since this is just a normal local-file repo.
    MAVEN_REPO_DIR="$PROJECT_ROOT/vendor/litert-android-maven"
    COORD_DIR="$MAVEN_REPO_DIR/com/google/ai/edge/litertlm/litertlm-android/$LITERT_VER"
    rm -rf "$MAVEN_REPO_DIR"
    mkdir -p "$COORD_DIR"
    cp "$VENDOR_AAR" "$COORD_DIR/litertlm-android-$LITERT_VER.aar"
    cat > "$COORD_DIR/litertlm-android-$LITERT_VER.pom" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.google.ai.edge.litertlm</groupId>
  <artifactId>litertlm-android</artifactId>
  <version>$LITERT_VER</version>
  <packaging>aar</packaging>
  <name>LiteRT-LM Android API (vendored local rebuild)</name>
  <description>HEAD-of-main Bazel rebuild of LiteRT-LM. Served from vendor/litert-android-maven/ to bypass Google Maven during build.</description>
  <licenses>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
    </license>
  </licenses>
  <dependencies>
    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
      <version>2.13.2</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-reflect</artifactId>
      <version>2.2.21</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlinx</groupId>
      <artifactId>kotlinx-coroutines-android</artifactId>
      <version>1.9.0</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</project>
EOF
    echo "[litert-android] Populated local Maven repo with litertlm-android:$LITERT_VER."
  fi

  # Clean out any .so files left by the previous override-via-jniLibs strategy.
  # Now that the AAR provides them, leaving stale copies in the library's
  # jniLibs source set re-introduces the very duplicate-merge errors we just
  # got rid of.
  STALE_JNILIBS_DIR="$ANDROID_DIR/src/main/jniLibs/arm64-v8a"
  if [ -d "$STALE_JNILIBS_DIR" ] && ls "$STALE_JNILIBS_DIR"/*.so >/dev/null 2>&1; then
    rm -f "$STALE_JNILIBS_DIR"/*.so
    echo "[litert-android] Cleared stale .so files from src/main/jniLibs/arm64-v8a/ (now sourced from local AAR)."
  fi

  # Replace the module-level build.gradle. Our vendored copy switches the
  # litertlm-android dep from Google Maven to the local Maven repo populated
  # above. See vendor/litert-android-build/build.gradle for full rationale.
  PATCHED_GRADLE="$PROJECT_ROOT/vendor/litert-android-build/build.gradle"
  if [ -f "$PATCHED_GRADLE" ]; then
    cp "$PATCHED_GRADLE" "$ANDROID_DIR/build.gradle"
    echo "[litert-android] Replaced android/build.gradle with vendored copy (local Maven repo)."
  fi

  # Patch the root android/build.gradle so the local Maven repo's
  # exclusiveContent filter applies project-wide. allprojects.repositories
  # is added to every subproject BEFORE that subproject's own repositories
  # block, so declaring exclusiveContent only inside the library is
  # shadowed: Gradle finds com.google.ai.edge.litertlm:litertlm-android on
  # google() (inherited from allprojects) and quietly downloads the
  # published Maven AAR — which has a different .so set than our
  # HEAD-of-main rebuild, leaving 6 of 9 arm64 .so out of the APK.
  # We must declare exclusiveContent at the allprojects level too, so
  # Gradle never queries google() for this group at all.
  #
  # android/build.gradle is gitignored (regenerated by `expo prebuild`),
  # so we re-apply the patch on every install. Idempotent: skips if the
  # marker line is already present.
  ROOT_GRADLE="$PROJECT_ROOT/android/build.gradle"
  if [ -f "$ROOT_GRADLE" ]; then
    if grep -q "exclusiveContent" "$ROOT_GRADLE" 2>/dev/null; then
      echo "[litert-android] Root build.gradle already patched with exclusiveContent — skipping."
    else
      awk '
        /^allprojects \{$/ {
          in_allprojects = 1
          print
          next
        }
        in_allprojects && /^  repositories \{$/ {
          print
          print "    // exclusiveContent: route com.google.ai.edge.litertlm to our local"
          print "    // Maven repo only. Patched in by scripts/install-litert-frameworks.sh."
          print "    // See app/mobile/scripts/install-litert-frameworks.sh + the same blocks"
          print "    // in vendor/litert-android-build/build.gradle for full rationale."
          print "    exclusiveContent {"
          print "      forRepository {"
          print "        maven {"
          print "          url = uri(\"${rootDir}/../vendor/litert-android-maven\")"
          print "        }"
          print "      }"
          print "      filter {"
          print "        includeGroup(\"com.google.ai.edge.litertlm\")"
          print "      }"
          print "    }"
          in_allprojects = 0
          next
        }
        { print }
      ' "$ROOT_GRADLE" > "$ROOT_GRADLE.tmp" && mv "$ROOT_GRADLE.tmp" "$ROOT_GRADLE"
      echo "[litert-android] Patched root android/build.gradle with exclusiveContent for litertlm group."
    fi
  fi

  # Replace LiteRTLMInitProvider.kt with our vendored copy. Upstream version
  # calls close() on every loaded LLM at TRIM_MEMORY_RUNNING_LOW (level 10),
  # which fires on routine app backgrounding and any moderate memory event —
  # that silently killed the loaded 2.58 GB Gemma 4 engine and forced a
  # ~30 s reload on next chat send. Our vendored copy raises the threshold
  # to TRIM_MEMORY_COMPLETE (80) so the engine survives normal navigation
  # and only releases when the OS is about to kill the app outright.
  PATCHED_INIT_KT="$PROJECT_ROOT/vendor/litert-android-kotlin/LiteRTLMInitProvider.kt"
  DEST_INIT_KT="$ANDROID_DIR/src/main/java/dev/litert/litertlm/LiteRTLMInitProvider.kt"
  if [ -f "$PATCHED_INIT_KT" ] && [ -d "$(dirname "$DEST_INIT_KT")" ]; then
    cp "$PATCHED_INIT_KT" "$DEST_INIT_KT"
    echo "[litert-android] Replaced LiteRTLMInitProvider.kt with vendored copy (raised TRIM_MEMORY threshold)."
  fi

  # Replace HybridLiteRTLM.kt with our vendored copy. Upstream passes a
  # default maxTokens=1024 through to EngineConfig.maxNumTokens, which the
  # Kotlin SDK + JNI shim then route into the C++ engine's max_num_tokens
  # setting. That value is the KV-cache *context length*, not a generation
  # cap — capping it at 1024 below Gemma 4 E2B's compiled prefill graph
  # caused the first prefill invocation to fail with
  #   tflite/kernels/dynamic_update_slice.cc:70
  #     SizeOfDimension(update, i) <= SizeOfDimension(operand, i)
  # iOS already documented + side-stepped this (see HybridLiteRTLM.cpp);
  # our vendored Kotlin copy applies the same fix on Android by simply
  # not setting maxNumTokens, letting the C++ default heuristic pick the
  # model's compiled context length.
  PATCHED_HYBRID_KT="$PROJECT_ROOT/vendor/litert-android-kotlin/HybridLiteRTLM.kt"
  DEST_HYBRID_KT="$ANDROID_DIR/src/main/java/com/margelo/nitro/dev/litert/litertlm/HybridLiteRTLM.kt"
  if [ -f "$PATCHED_HYBRID_KT" ] && [ -d "$(dirname "$DEST_HYBRID_KT")" ]; then
    cp "$PATCHED_HYBRID_KT" "$DEST_HYBRID_KT"
    echo "[litert-android] Replaced HybridLiteRTLM.kt with vendored copy (omit maxNumTokens to avoid DYNAMIC_UPDATE_SLICE)."
  fi
elif [ -f "$VENDOR_AAR" ] && [ ! -d "$ANDROID_DIR" ]; then
  echo "[litert-android] Vendored AAR present but react-native-litert-lm/android is missing — skipping."
fi

# Note: previously this script also pinned package.json's
# litertLm.androidMavenVersion to "0.11.0-rc1" so the upstream build.gradle
# would resolve a Gemma-4-compatible Maven coord. With the flatDir switch
# above, the Maven dep is gone entirely and androidMavenVersion is unused —
# so the pin step has been removed.

echo "[litert-frameworks] ✅ iOS + Android vendored artifacts installed. Run \`npx pod-install ios\` next."
